### ISSUE TITLE
further search work

### ISSUE THREAD

**Issue by aliceriot** [mitodl/hugo-course-publisher#178]
further work to do on the search:

- [x] add support for paging to the search result UI
- [x] limit search to only courses (no videos and so on) 
- [x] remove open_content_icon.png which is a holdover from open.mit.edu 
- [x] add topics facet
- [x] #217 add department facet
- [x] #216 add support for level facets
- [x] #136 link from search results to courses
- [x] #207 add support for searching for file resources
- [x] #230 remove redundant "course" label
- [x] add UI for search suggestions
- [ ] split JS bundle into specific bundles: one for homepage, one for general course pages, one for search page, one for video gallery, one for photo gallery. should mean that for each page the user has to download less JS.

**Comment by aliceriot** [comment]
@pdpinch @abdulkdawson I was thinking I could work on a UI for search suggestions (like we have on Open already). I didn't find a design for it going through invision though - is that something we want to work on next? the backend stuff is all already in place for it, so it would just be a matter of adding some UI code.

**Comment by aliceriot** [comment]
I opened another issue (#317 ) for the remaining item here, so going to close now.
