### ISSUE TITLE
Publish static site to S3 bucket 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#184]
As an engineer, I'd like to use Slack to build and release the OCW site, similar to what we do with other projects. 

I want to be able to decide when a release will be built, since it may take some time to rebuild all the courses on the site. 

#### Acceptance Criteria:

- [ ] Set up a Travis job that will run hugo (and optionally the zip build), and upload the output to S3
- [ ] Set up a github action so that whenever the release branch is updated it will trigger a build
- [ ] Connect the github branches to the Doof chatbot so it can be used to trigger releases.
- [ ] For each build, a new directory will be created in the bucket with a datestamp. This allows for quick rollbacks.

**Comment by blarghmatey** [comment]
Since this was first written we have changed direction slightly. The updated workflow and acceptance criteria are:
- [ ] Create an EC2 instance with the ocw-to-hugo and hugo-course-publisher repositories installed
- [ ] Configure the Caddy server on the EC2 build box to accept inbound webhooks from GitHub to trigger content builds
- [ ] Create a GitHub webhook to send to the EC2 build box

## Optional enhancements
- [ ] Configure the Caddy server to accept inbound event hooks from S3 to run ocw-to-hugo and hugo-course-publisher
- [ ] Configure S3 to send event notifications to the EC2 build box on content changes in the source S3 bucket
