### ISSUE TITLE
Resource Search

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#207]
As a user, I'd like to be able to search for resources within OCW courses, in particular videos, PDFs and HTML pages. 

#### Designs and Mockups

TBD

#### Acceptance Criteria:

- [x] Update open search index to support 
- [x] add resource support to open search APIs
- [x] simple text search front end in OCW NextGen that returns cards
- [ ] add facets (TBD)

**Comment by pdpinch** [comment]
I'm going to close this epic. I'll open additional issues for facets once we have a clearer idea what needs to be done.
